In [48]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pickle

In [49]:
df = pd.read_csv("/content/hospital_dataset_120_records.csv")

In [50]:
df

     Fever  Cough  Headache  Fatigue   Disease
0        1      1         1        1       Flu
1        1      1         1        1       Flu
2        1      1         1        1       Flu
3        1      1         1        1       Flu
4        1      1         1        1       Flu
..     ...    ...       ...      ...       ...
115      0      0         1        1  Migraine
116      0      0         1        1  Migraine
117      0      0         1        1  Migraine
118      0      0         1        1  Migraine
119      0      0         1        1  Migraine

[120 rows x 5 columns]

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Fever     120 non-null    int64
 1   Cough     120 non-null    int64
 2   Headache  120 non-null    int64
 3   Fatigue   120 non-null    int64
 4   Disease   120 non-null    object
dtypes: int64(4), object(1)
memory usage: 4.8+ KB

In [52]:
df.isnull().sum()

Fever       0
Cough       0
Headache    0
Fatigue     0
Disease     0
dtype: int64

In [53]:
df.head()

   Fever  Cough  Headache  Fatigue Disease
0      1      1         1        1     Flu
1      1      1         1        1     Flu
2      1      1         1        1     Flu
3      1      1         1        1     Flu
4      1      1         1        1     Flu

In [54]:
df.shape

(120, 5)

In [55]:
x = ["Fever", "Cough", "Headache","Fatigue"]
y = ["Disease"]

In [56]:
x_train,x_test,y_train,y_test = train_test_split(df[x],df[y],train_size=0.2,random_state=42)

In [57]:
model = DecisionTreeClassifier()

In [58]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [59]:
y_pred = model.predict(x_test)

In [60]:
accuracy = accuracy_score(y_test, y_pred)

In [61]:
accuracy

1.0

In [62]:
pickle.dump(model, open("model.pkl", "wb"))
print("model saved succesfully")

model saved succesfully